# PyTorch Tensor Cheat Sheet

## 创建Tensor

In [13]:
import torch

# TODO: create tensor

## 改变形状

## 广播机制

许多PyTorch操作支持Numpy的[广播语义](https://numpy.org/doc/stable/user/basics.broadcasting.html)

广播就是对于两个形状不同的tensor，把一个tensor的某些维度自动地扩展/广播，使得两个tensor的形状相同，避免了不必要的复制。

上面的定义暗示了不是任何两个tensor都可以进行广播，它们的形状必须是兼容的，或者说**可广播的**（boradcastable）。

当满足下面条件时，两个tensor是可广播的：

* 每个tensor都至少有1个维度（及形状都不能是`(0, )`）
* 从最后一个维度开始往前进行比较，两个维度必须是相等的，或者其中一个为1，或者其中一个不存在

下面是一些例子：

In [14]:
a = torch.randn(5, 3, 4, 1)
b = torch.randn(   3, 1, 1)
(a + b).shape  # of shape (5, 3, 4, 1)

torch.Size([5, 3, 4, 1])

In [15]:
a = torch.randn(5, 3, 1, 2)
b = torch.randn(5, 1, 4, 2)
(a + b).shape  # of shape (5, 3, 4, 1)

torch.Size([5, 3, 4, 2])

In [18]:
a = torch.randn(5, 3, 1, 2)
b = torch.randn(5, 2, 4, 2)
(a + b).shape  # 错误：第二个维度不可进行广播

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

 注意广播后的结果有可能不同于原来的任何一个矩阵，而in-place操作（例如`Tensor.add_`等末尾带`_`的函数，或者它的等价形式`a += b`）不允许改变原有tensor的形状，这样的话一些in-place的操作有可能出发`RuntimeError`

In [24]:
a = torch.randn(3, 1, 4)
b = torch.randn(3, 5, 1)
a += b  # RuntimeError

RuntimeError: output with shape [3, 1, 4] doesn't match the broadcast shape [3, 5, 4]

在老版本的PyTorch中，一些逐点（pointwise）操作只要求两个tensor的元素个数一样，然后把两个tensor视作一维后逐点操作，而在引入广播语义后，这些操作会对两个tensor做广播，这可能导致一些向后兼容性问题。

In [29]:
a = torch.randn(4, 1)
b = torch.randn(   4)
(a + b).shape  # result is of shape(4, 1) in prior versions

torch.Size([4, 4])

## 加法和乘法

### `torch.mul`和`__mul__`

`torch.mul(input, other, *, out=None)`

当进行诸如`a + b`，`a`


In [5]:
import torch

# __mul__, torch.mul, torch.multiply, torch.mm, torch.matmul, torch.bmm, torch.dot

# __mul__, torch.mul

a = torch.randn(3, 3)
print(a)

b = torch.randn(3, 3)
print(b)

c = a * b

a[0][0] * b[0][0]

print(c)

tensor([[-0.4034, -0.5670,  0.7556],
        [ 2.0752, -0.7757, -0.8097],
        [-1.5358, -0.6654,  0.1280]])
tensor([[-1.4275, -1.4594,  0.6846],
        [-0.4586, -0.8079, -0.8288],
        [ 0.0135,  0.1691,  3.1267]])
tensor([[ 0.5759,  0.8274,  0.5172],
        [-0.9518,  0.6267,  0.6711],
        [-0.0208, -0.1125,  0.4003]])


## 其他常用操作